brand:
  name: Kunal Gupta
menu-string: Menu

nav:
  - title: Skills
    url: 'skills'
  - title: Projects
    url: '#projects'
  - title: Experience
    url: '#experience'
  - title: Connect
    url: '#connect'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Kunal Gupta 2019

social-buttons:
  - icon: fa fa-twitter
    url: '#'
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/iamkunalgupta'
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/kunalgupta777'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
